<a href="https://colab.research.google.com/github/rajenbala/dlaicourse/blob/master/Tensorflow_Master_Reference.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
# Fundamentals of Tensorflow

import tensorflow as tf
print(tf.__version__)


2.4.1


In [8]:
## Creating Tensors with Tensor Constant

scalar=tf.constant(9.8)
scalar

<tf.Tensor: shape=(), dtype=float32, numpy=9.8>

In [9]:
vector =tf.constant([2,3,9])
vector.ndim

1

In [10]:
matrix=tf.constant([[2,4],[3,4]])
matrix.ndim

2

In [11]:
myTensor =tf.constant([[
                      [1,2,3],
                      [2,3,5]],
                     [[3,4,5],
                      [4,5,6]]])
myTensor.ndim

3

In [12]:
myTensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [2, 3, 5]],

       [[3, 4, 5],
        [4, 5, 6]]], dtype=int32)>

In [13]:
tensor_rank4 = tf.constant([[[
                              [2,3],[4,5]
                              ],
                             [
                              [4,5],[6,7]
                             ],
                             [
                              [33,30],[6,9]
                             ]
                             ],
                            [[
                              [63,2],[14,18]
                            ],
                             [
                              [33,30],[6,9]
                             ],
                             [
                              [33,30],[6,9]
                             ]
                            ],
                            [[
                              [63,2],[14,18]
                            ],
                             [
                              [33,30],[6,9]
                             ],
                             [
                              [33,30],[6,9]
                             ]
                            ],
                            [[
                              [63,2],[14,18]
                            ],
                             [
                              [33,30],[6,9]
                             ],
                             [
                              [33,30],[6,9]
                             ]
                            ]
                            ])
tensor_rank4.ndim

4

In [14]:
tensor_rank4

<tf.Tensor: shape=(4, 3, 2, 2), dtype=int32, numpy=
array([[[[ 2,  3],
         [ 4,  5]],

        [[ 4,  5],
         [ 6,  7]],

        [[33, 30],
         [ 6,  9]]],


       [[[63,  2],
         [14, 18]],

        [[33, 30],
         [ 6,  9]],

        [[33, 30],
         [ 6,  9]]],


       [[[63,  2],
         [14, 18]],

        [[33, 30],
         [ 6,  9]],

        [[33, 30],
         [ 6,  9]]],


       [[[63,  2],
         [14, 18]],

        [[33, 30],
         [ 6,  9]],

        [[33, 30],
         [ 6,  9]]]], dtype=int32)>

In [15]:
#Creating Tensor with tf.variable
changebleTensors = tf.Variable([2,3])
changebleTensors

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2, 3], dtype=int32)>

In [16]:
changebleTensors[0].assign(3)
changebleTensors

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 3], dtype=int32)>

In [17]:
## Creating Random Tensors

## Random Variables Normally distributed
tf.random.normal(shape=(2,3,4))


<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[ 0.03725741,  0.51034856,  0.81363785, -0.22474867],
        [-0.11332719, -1.256693  , -0.04462241,  0.645737  ],
        [ 0.4552612 ,  0.13111697, -0.04129713, -0.65996575]],

       [[-0.7552684 ,  2.336664  , -1.2945317 ,  0.45867616],
        [-0.6994845 ,  0.6278672 ,  0.76587874,  0.8116292 ],
        [-0.87639105, -0.34157503,  0.3728915 , -1.1019475 ]]],
      dtype=float32)>

In [18]:
## Random Variable Uniformly distributed

tf.random.uniform(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.50081635, 0.90957344, 0.4244337 ],
       [0.6466601 , 0.46901035, 0.7359233 ]], dtype=float32)>

In [19]:
random_replicable = tf.random.Generator.from_seed(33)
random1=random_replicable.normal(shape=(2,2))
random1


<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.1589871 ,  1.302304  ],
       [ 0.9592239 ,  0.85874265]], dtype=float32)>

In [20]:
random_replicable = tf.random.Generator.from_seed(33)
random2=random_replicable.normal(shape=(2,2))
random2

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.1589871 ,  1.302304  ],
       [ 0.9592239 ,  0.85874265]], dtype=float32)>

In [21]:
random1,random2,random1==random2

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-0.1589871 ,  1.302304  ],
        [ 0.9592239 ,  0.85874265]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-0.1589871 ,  1.302304  ],
        [ 0.9592239 ,  0.85874265]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True]])>)

In [22]:
## Shuffling the tensor
newTensor=tf.constant([1,2,4,5,6,8,0])
newTensor

<tf.Tensor: shape=(7,), dtype=int32, numpy=array([1, 2, 4, 5, 6, 8, 0], dtype=int32)>

In [23]:
tf.random.set_seed(21)
tf.random.shuffle(newTensor,seed=21)


<tf.Tensor: shape=(7,), dtype=int32, numpy=array([6, 4, 2, 5, 0, 8, 1], dtype=int32)>

In [24]:
tf.random.shuffle(newTensor,seed=21)

<tf.Tensor: shape=(7,), dtype=int32, numpy=array([4, 8, 5, 2, 6, 1, 0], dtype=int32)>

In [25]:
## Converting Numpy to Tensor

import numpy as np

numpyArray= np.arange(1,21,dtype=float)
numpyArray


array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20.])

In [26]:
type(numpyArray)
numpyArray.shape
numpyArray.size

20

In [27]:
numpyTensor = tf.constant(numpyArray,shape=(2,5,2))
numpyTensor

<tf.Tensor: shape=(2, 5, 2), dtype=float64, numpy=
array([[[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]],

       [[11., 12.],
        [13., 14.],
        [15., 16.],
        [17., 18.],
        [19., 20.]]])>

Getting Information from Tensor

1. Rank
2.Shape
3. Axis
4. Size


In [39]:
#Getting Info from Tensorflow

print(numpyTensor.shape)
print(numpyTensor.ndim)
print(tf.size(numpyTensor))

print(tf.size(numpyTensor).numpy())


(2, 5, 2)
3
tf.Tensor(20, shape=(), dtype=int32)
20


In [37]:
numpyTensor[1,2:,:3]

<tf.Tensor: shape=(3, 2), dtype=float64, numpy=
array([[15., 16.],
       [17., 18.],
       [19., 20.]])>

In [41]:
## Indexing and retrieving Tensor

dummyTensor = tf.zeros(shape=(3,4,5,3))
dummyTensor

<tf.Tensor: shape=(3, 4, 5, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


      

In [47]:
#Getting first 2 values of each dimension

dummyTensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [52]:
#Getting first 2 values of each dimension except one dimension

dummyTensor[:2,:2,:2,:]

<tf.Tensor: shape=(2, 2, 2, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>

In [53]:
dummyTensor.shape

TensorShape([3, 4, 5, 3])

In [54]:
3*4*5*3

180

In [55]:
18*5*2

180

In [58]:
tf.reshape(dummyTensor,shape=(18,5,2),name="reShapedTensor")

<tf.Tensor: shape=(18, 5, 2), dtype=float32, numpy=
array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0

In [62]:
#Adding a dimension
matrix.ndim
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [3, 4]], dtype=int32)>

In [61]:
newMatrix=matrix[...,tf.newaxis]
newMatrix

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [4]],

       [[3],
        [4]]], dtype=int32)>

In [66]:
tf.expand_dims(newMatrix,axis=3)

<tf.Tensor: shape=(2, 2, 1, 1), dtype=int32, numpy=
array([[[[2]],

        [[4]]],


       [[[3]],

        [[4]]]], dtype=int32)>

In [93]:
### Manipulating Tensors
## Basic Operation +,-,*,/


randomTensor= tf.random.normal(shape=(2,3))
randomTensor

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.02590763,  0.25280836,  0.77750325],
       [ 0.8310911 ,  0.5512013 , -0.59923774]], dtype=float32)>

In [97]:
randomIntegers= np.random.rand(3,2)
randomIntegers

array([[0.41305272, 0.17694314],
       [0.14437343, 0.64105902],
       [0.9565581 , 0.66566449]])

In [98]:
newRandomTensor=tf.constant(randomIntegers,dtype="float32")
newRandomTensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.4130527 , 0.17694314],
       [0.14437343, 0.64105904],
       [0.9565581 , 0.6656645 ]], dtype=float32)>

In [96]:
newRandomTensor+5,tf.add(newRandomTensor,5),newRandomTensor+5==tf.add(newRandomTensor,5)

(<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[5.321678 , 5.145473 , 5.427674 ],
        [5.1357193, 5.552322 , 5.701884 ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[5.321678 , 5.145473 , 5.427674 ],
        [5.1357193, 5.552322 , 5.701884 ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=bool, numpy=
 array([[ True,  True,  True],
        [ True,  True,  True]])>)

In [99]:
## Matrix Multiplication

tf.matmul(randomTensor,newRandomTensor)


<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.79092705,  0.6842056 ],
       [-0.15034246,  0.10151711]], dtype=float32)>

In [107]:
tf.tensordot(randomTensor,newRandomTensor,axes=2). # Check whats axes



<tf.Tensor: shape=(), dtype=float32, numpy=0.8288279>

In [110]:
newRandomTensorFloat16=tf.cast(newRandomTensor,dtype=tf.float64)
newRandomTensorFloat16

<tf.Tensor: shape=(3, 2), dtype=float64, numpy=
array([[0.41305271, 0.17694314],
       [0.14437343, 0.64105904],
       [0.95655811, 0.66566449]])>